// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Projeto360.Repository.Migrations
{
    [DbContext(typeof(Projeto360Context))]
    [Migration("20260407175419_CorrecaoSQLite")]
    partial class CorrecaoSQLite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Projeto360.Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Equipes", (string)null);
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Historia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetoID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProjetoID");

                    b.ToTable("Historias", (string)null);
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Projeto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Projetos", (string)null);
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Sprint", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ProjetoID");

                    b.ToTable("Sprints", (string)null);
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Estimativa")
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoriaID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SprintID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTarefa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("HistoriaID");

                    b.HasIndex("ProjetoID");

                    b.HasIndex("SprintID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Tarefas", (string)null);
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.TwoFactorToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expiracao")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("TwoFactorTokens");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Ativo = true,
                            Email = "admin.tarefa360@gmail.com",
                            Nome = "Administrador",
                            Senha = "$2a$11$p2pVD8BJegQOpFHkZfX6QeAhqdmt94VQy326qIHRWSikWPX2SRdvC",
                            TipoUsuario = 1
                        });
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.UsuarioEquipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PapeisEquipe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("EquipeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosEquipes", (string)null);
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Historia", b =>
                {
                    b.HasOne("Projeto360.Domain.Entities.Projeto", "Projeto")
                        .WithMany("Historias")
                        .HasForeignKey("ProjetoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Sprint", b =>
                {
                    b.HasOne("Projeto360.Domain.Entities.Projeto", "Projeto")
                        .WithMany("Sprints")
                        .HasForeignKey("ProjetoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("Projeto360.Domain.Entities.Historia", "Historia")
                        .WithMany("Tarefas")
                        .HasForeignKey("HistoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto360.Domain.Entities.Projeto", "Projeto")
                        .WithMany("Tarefas")
                        .HasForeignKey("ProjetoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto360.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Tarefas")
                        .HasForeignKey("SprintID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto360.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historia");

                    b.Navigation("Projeto");

                    b.Navigation("Sprint");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.TwoFactorToken", b =>
                {
                    b.HasOne("Projeto360.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TwoFactorTokens")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.UsuarioEquipe", b =>
                {
                    b.HasOne("Projeto360.Domain.Entities.Equipe", "Equipe")
                        .WithMany("UsuariosEquipe")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto360.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioEquipes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("UsuariosEquipe");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Historia", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Projeto", b =>
                {
                    b.Navigation("Historias");

                    b.Navigation("Sprints");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Projeto360.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Tarefas");

                    b.Navigation("TwoFactorTokens");

                    b.Navigation("UsuarioEquipes");
                });
#pragma warning restore 612, 618
        }
    }
}
